# Generated by Django 5.1.1 on 2024-10-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante_curso', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecurso',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'Estudiante'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='persona.persona'),
        ),
    ]
