# Generated by Django 5.1.1 on 2024-10-07 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.persona'),
        ),
        migrations.AlterModelTable(
            name='curso',
            table='Curso',
        ),
    ]
