# Generated by Django 5.1.1 on 2024-10-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_curso_capacidad_max'),
        ('curso', '0003_alter_curso_estudiantes'),
    ]

    operations = [
    ]
